require('configs.colorscheme')
-- require('configs.fugitive')
-- require('configs.devicon')
-- require('config.telescope')
-- require('configs.compe')
-- require('configs.lspkind')
-- require('configs.treesitter')
