require('config.colorscheme')
require('config.fugitive')
require('config.neogit')
require('config.devicon')
require('config.telescope')
require('config.compe')
require('config.lspkind')
require('config.treesitter')
